# Generated by Django 5.2.6 on 2025-10-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('random_wish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='using_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
