# Generated by Django 5.2.6 on 2025-10-25 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DriveLicense',
            fields=[
                ('number', models.CharField(primary_key=True, serialize=False)),
                ('human', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_license', to='relations_app.human')),
            ],
        ),
    ]
