# Generated by Django 5.2.6 on 2025-10-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations_app', '0005_remove_student_courses_alter_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='relations_app.student'),
        ),
    ]
